work_dir: ./work_dir/ntu/xsub/msg3d_joint

# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/train_data_joint_ex_5.npy
  label_path: ./data/train_label_r_ex_5.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/val_data_joint_ex_5.npy
  label_path: ./data/val_label_r_ex_5.pkl

# model
model: model.msg3d.Model
model_args:
  num_class: 2
  num_point: 25
  num_person: 1
  num_gcn_scales: 13 # `num_scales` == `K + 1` in the paper
  num_g3d_scales: 6
  graph: graph.ntu_rgb_d.AdjMatrixGraph

# optim
weight_decay: 0.0005
base_lr: 0.05
step: [30, 40]

# training
num_epoch: 20
device: [4, 5, 6, 7]
batch_size: 8
forward_batch_size: 4
test_batch_size: 8
nesterov: True
